name: Deploy

on:
  push:
    branches:
      - main

env:
  SHUTUP: 1
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: [self-hosted, public]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Prepare ssh key
        run: |
          eval $(ssh-agent -s)
          ssh-add -D
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

      - name: Build and push image
        uses: dagger/dagger-for-github@v8.1.0
        with:
          version: v0.18.10
          verb: call
          module: git@github.com:prorocketeers/dagger-pipelines.git/docker@v0.1.0
          args: >-
            build
            --app-src .
            --git-src .
            --release dev
            --reg-username $HARBOR_USERNAME 
            --reg-password env:HARBOR_PASSWORD
            --image-name prorocketeers/challenger-soundboard 
            --registry harbor.intra.prorocketeers.com

      - name: Deploy
        uses: dagger/dagger-for-github@v8.1.0
        with:
          version: v0.18.10
          verb: call
          module: git@github.com:prorocketeers/dagger-pipelines.git/deploy
          args: >-
            deploy
            --tag ${{ github.sha }}
            --token ${{ secrets.ARGO_TRIGGER_TOKEN }}
            --values-file "challenger-soundboard/dev/values.yaml"
            --repo "argo-repo-production"